export const ERROR_SCHEDULE_GROUP = 'ERROR_SCHEDULE_GROUP'
export const SUCCESS_SCHEDULE_GROUP = 'SUCCESS_SCHEDULE_GROUP'
export const FETCHING_SCHEDULE_GROUP = 'FETCHING_SCHEDULE_GROUP'
export const CLEAR_SCHEDULE_GROUP = 'CLEAR_SCHEDULE_GROUP'

export const ERROR_GROUPS = 'ERROR_GROUPS'
export const SUCCESS_GROUPS = 'SUCCESS_GROUPS'
export const FETCHING_GROUPS = 'FETCHING_GROUPS'

export const SET_DATE_TOGGLE_WEEK = 'SET_DATE_TOGGLE_WEEK'
export const SET_DATE = 'SET_DATE'
export const TOGGLE_OFF = 'TOGGLE_OFF'

export const SET_ALL = 'SET_ALL'
export const SET_GROUP_ID = 'SET_GROUP_ID'
export const SET_GROUP_NAME = 'SET_GROUP_NAME'
export const SET_FACULTY = 'SET_FACULTY'
export const SET_THEME = 'SET_THEME'
export const SET_PLATFORM = 'SET_PLATFORM'
