export const ERROR_SCHEDULE = 'ERROR_SCHEDULE'
export const SUCCESS_SCHEDULE = 'SUCCESS_SCHEDULE'
export const FETCHING_SCHEDULE = 'FETCHING_SCHEDULE'
export const CLEAR_SCHEDULE = 'CLEAR_SCHEDULE'

export const ERROR_GROUPS = 'ERROR_GROUPS'
export const SUCCESS_GROUPS = 'SUCCESS_GROUPS'
export const FETCHING_GROUPS = 'FETCHING_GROUPS'

export const ERROR_TEACHERS = 'ERROR_TEACHERS'
export const SUCCESS_TEACHERS = 'SUCCESS_TEACHERS'
export const FETCHING_TEACHERS = 'FETCHING_TEACHERS'

export const ERROR_TEACHER_GROUPS = 'ERROR_TEACHER_GROUPS'
export const SUCCESS_TEACHER_GROUPS = 'SUCCESS_TEACHER_GROUPS'
export const FETCHING_TEACHER_GROUPS = 'FETCHING_TEACHER_GROUPS'

export const ERROR_GROUP_TEACHERS = 'ERROR_GROUP_TEACHERS'
export const SUCCESS_GROUP_TEACHERS = 'SUCCESS_GROUP_TEACHERS'
export const FETCHING_GROUP_TEACHERS = 'FETCHING_GROUP_TEACHERS'

export const ERROR_DISCIPLINES = 'ERROR_DISCIPLINES'
export const SUCCESS_DISCIPLINES = 'SUCCESS_DISCIPLINES'
export const FETCHING_DISCIPLINES = 'FETCHING_DISCIPLINES'

export const SET_DATE_TOGGLE_WEEK = 'SET_DATE_TOGGLE_WEEK'
export const SET_DATE = 'SET_DATE'
export const SET_CURRENT_DATE = 'SET_CURRENT_DATE'
export const TOGGLE_OFF = 'TOGGLE_OFF'

export const SET_ALL = 'SET_ALL'
export const SET_GROUP = 'SET_GROUP'
export const SET_TEACHER = 'SET_TEACHER'
export const SET_THEME = 'SET_THEME'
export const SET_PLATFORM = 'SET_PLATFORM'
export const SET_POST = 'SET_POST'
export const SET_BRIDGE_SUPPORT = 'SET_BRIDGE_SUPPORT'
export const ADD_HELPERS = 'ADD_HELPERS'
