export const enum VIEW_ENUM {
  SCHEDULE = 'SCHEDULE',
  PROFILE = 'PROFILE',
}

export const enum PANEL_PROFILE_ENUM {
  MAIN = 'MAIN',
  DISCIPLINES = 'DISCIPLINES',
  STATEMENTS = 'STATEMENTS',
  LK = 'LK',
  SETTINGS = 'SETTINGS',
  GROUPS_OF_TEACHER = 'GROUPS_OF_TEACHER',
  TEACHERS_OF_GROUP = 'TEACHERS_OF_GROUP',
  SEARCH_GROUP = 'SEARCH_GROUP',
  SEARCH_TEACHER = 'SEARCH_TEACHER',
  SEARCH_CLASSROOM = 'SEARCH_CLASSROOM',
}

export const enum MODAL_PROFILE_ENUM {
  FILTRES_OF_GROUP = 'FILTRES_OF_GROUP',
}

export const enum PANEL_SCHEDULE_ENUM {
  MAIN = 'MAIN',
  NOTES = 'NOTES',
}
